version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      RAILS_ENV: development
    env_file: .env
    expose:
      - 5432:5432
    restart: unless-stopped

  web:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.Api
    environment:
      RAILS_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      GMAIL_USERNAME: ${GMAIL_USERNAME}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}

    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
    data:
      driver: local